name: CI-CD
on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Building
        run: npm run build

  DEV:
    needs: Build
    if: ${{ github.ref == 'refs/heads/development' }}
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: 'https://...../web/index.html'
    steps:
      - uses: actions/checkout@v2

      # Setup AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Sync files with AWS S3 bucket
      - name: Deploying
        run: aws s3 sync ${{ secrets.SOURCE_DIRECTORY }} ${{ secrets.AWS_S3_BUCKET }}

  STG:
    needs: Build
    if: ${{ github.ref == 'refs/heads/release' }}
    runs-on: ubuntu-latest
    environment:
      name: STG
      url: 'https://...../web/index.html'
    steps:
      - uses: actions/checkout@v2

      # Setup AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Sync files with AWS S3 bucket
      - name: Deploying
        run: aws s3 sync ${{ secrets.SOURCE_DIRECTORY }} ${{ secrets.AWS_S3_BUCKET }}

  PRD:
    needs: Build
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: PRD
      url: 'https://...../web/index.html'
    steps:
      - uses: actions/checkout@v2

      # Setup AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Sync files with AWS S3 bucket
      - name: Deploying
        run: aws s3 sync ${{ secrets.SOURCE_DIRECTORY }} ${{ secrets.AWS_S3_BUCKET }}
